import:
 - ~/.config/alacritty/themes/themes/kanadawa_dragon.yaml

shell:
  program: /usr/bin/fish

font:
  normal:
    family: iosevka
    style: fixed

  bold:
    family: iosevka
    style: Bold

  italic:
    family: iosevka
    style: Italic

  bold_italic:
    family: iosevka
    style: Bold Italic

  size: 13
